Fix GCC compile error due to incompatible type cast
GCC 9 complains about these reinterpret_cast expressions because of the
different return value:

  error: cast between incompatible function types from ‘void (*)(JNIEnv*, jni::jobject*, jni::jobject*)’ {aka ‘void (*)(_JNIEnv*, jni::jobject*, jni::jobject*)’} to ‘jboolean (*)(JNIEnv*, jobject, jobject)’ {aka ‘unsigned char (*)(_JNIEnv*, _jobject*, _jobject*)’}

Fix by using void as return value.